steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/size-ai/app', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/size-ai/app']
images: ['gcr.io/size-ai/app']